lsi: false
safe: true
source: first_lesson
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
